---
# Project Information
site_name: CumulusCI JIRA Plugin
site_author: Jason Lantz
site_description: A plugin for CumulusCI that adds a service to connect to Atlassian's Jira including an integration with CumulusCI's release notes parser

# Repository information
repo_name: muselab-d2x/CumulusCI-Jira
repo_url: https://github.com/muselab-d2x/CumulusCI-Jira
edit_uri: ""

# Copyright
copyright: Copyright &copy; 2023 Jason Lantz

# Configuration
theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.instant
    - navigation.tabs
  language: en

# Footer
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/muselab-d2x
      name: muselab-d2x on GitHub

# Page tree
nav:
  - Home: index.md
